#!/bin/bash

usage="Usage: dimi [ info | stake | latest | dust ] \n \n
	info: Check basic info. \n
	stake: Enables staking; Passes password without storing it in memory. \n
	latest: Compares latest block with the Diminutivecoin hosted block explorer. \n
	dust: Prunes dust from wallet. Dust is defined as less than .00000002DIMI. Requires jq. \n"

dimic='/usr/local/bin/diminutivecoin-cli -datadir=/var/lib/.diminutivecoin/'

case $1 in

info )
	$dimic getwalletinfo | egrep "balance|staked_balance|txcount|unconfirmed_balance|immature_balance|total_balance";
	$dimic getnetworkinfo | egrep "subversion|connections";
	$dimic getinfo | egrep "blocks";
	$dimic getblockchaininfo | egrep "best";
	$dimic getstakinginfo | egrep "enabled|staking|netstakeweight|expectedtime";
;;

stake )
	echo 'enter Diminutivecoin Password'
	read -s DIMIPW
	$dimic walletpassphrase $DIMIPW 99999999 true
	DIMIPW=null
;;

latest )
	latest=$($dimic  getblockcount) && \
	    dminutivesight=$(curl -s https://node.diminutivecoin.com/insight-api/block-index/$latest? |  cut -d '"' -f4) && \
	    diminutivecoin=$($dimic  getblockhash $latest) && \
	    diff -sy --label Local <(echo $diminutivecoin) --label Explorer <(echo $diminutivesight)
;;

dust )
	IFS=$'\n';

/usr/local/bin/diminutivecoin-cli -datadir=/var/lib/.diminutivecoin/ listtransactions "*" 99999 | jq -r '.[] | select(.category != "send") | select(.amount < .00000002) | .txid' | uniq >txid.txt

	while read line; do
	        echo $line 
	        /usr/local/bin/diminutivecoin-cli -datadir=/var/lib/.diminutivecoin/ removeprunedfunds $(echo $line)
	done < "txid.txt"
;;

*)
    echo -e $usage
;;	

esac
